# Generated by Django 5.0 on 2025-05-14 09:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction_of_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бизнеса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направления бизнеса',
                'verbose_name_plural': 'Направления бизнеса',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рубрики')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('global_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.direction_of_business', verbose_name='Направление бизнеса')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Документ')),
                ('direction_of_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.direction_of_business', verbose_name='Направление бизнеса')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.section', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
