# Generated by Django 5.2.1 on 2025-06-03 10:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^(\\d{10}|\\d{12})$')], verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='ОГРН должен содержать 13 цифр', regex='^\\d{13}$')], verbose_name='ОГРН')),
                ('legal_form', models.TextField(verbose_name='Организационно-правовая форма')),
                ('company_group', models.TextField(verbose_name='Группа компаний')),
                ('status', models.TextField(verbose_name='Статус')),
                ('authorized_capital', models.TextField(verbose_name='Уставной капитал')),
                ('registrar', models.TextField(blank=True, null=True, verbose_name='Реестродержатель')),
                ('registrar_inn', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^(\\d{10}|\\d{12})$')], verbose_name='ИНН реестродержателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя/Наименование')),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^(\\d{10}|\\d{12})$')], verbose_name='ИНН')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_bodies', to='legal_opin.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Единоличный исполнительный орган',
                'verbose_name_plural': 'Единоличные исполнительные органы',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('credit_product_type', models.TextField(verbose_name='Вид кредитного продукта')),
                ('legal_entities', models.ManyToManyField(related_name='deals', to='legal_opin.legalentity', verbose_name='Юридические лица')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя/Наименование')),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^(\\d{10}|\\d{12})$')], verbose_name='ИНН')),
                ('share', models.TextField(blank=True, null=True, verbose_name='Доля')),
                ('share_info', models.TextField(blank=True, null=True, verbose_name='Информация о доле')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='legal_opin.legalentity', verbose_name='Юридическое лицо')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
