# Generated by Django 5.2.1 on 2025-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_opin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Юридическое лицо', 'verbose_name_plural': 'Юридические лица'},
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
