# Generated by Django 5.2.1 on 2025-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_opin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='confirmation_procedure',
            field=models.TextField(blank=True, null=True, verbose_name='Способ подтверждения принятия решения'),
        ),
    ]
