# Generated by Django 5.2.1 on 2025-08-22 10:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Направление деятельности Банка',
                'verbose_name_plural': 'Направления деятельности Банка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Вид правовой экспертизы')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Вид правовой экспертизы',
                'verbose_name_plural': 'Виды правовой экспертизы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Предмет правового анализа',
                'verbose_name_plural': 'Предметы правового анализа',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.TextField(verbose_name='Риск')),
                ('risk_factor', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Риск-факторы')),
                ('legal_basis', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Правовое обоснование')),
                ('negative_consequences', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Негативные последствия')),
                ('minimization_measures', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Меры минимизации')),
                ('associated_risks', models.TextField(verbose_name='Связанные риски')),
                ('info_about_risk_realization', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Информация о реализации риска')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.direction', verbose_name='Направление деятельности Банка, свойственное риску')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.kind', verbose_name='Вид правовой экспертизы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.subject', verbose_name='Предмет правового анализа')),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Риски',
                'ordering': ['risk'],
            },
        ),
    ]
