# Generated by Django 5.2.1 on 2025-06-03 10:17

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction_of_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бизнеса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Направления бизнеса',
                'verbose_name_plural': 'Направления бизнеса',
            },
        ),
        migrations.CreateModel(
            name='Doc_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рубрики')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('global_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.direction_of_business', verbose_name='Направление бизнеса')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рубрики')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('global_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.direction_of_business', verbose_name='Направление бизнеса')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('status', models.CharField(choices=[('active', 'Действующая редакция'), ('obsolete', 'Утратил силу')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_template', models.BooleanField(default=False, verbose_name='Это шаблон')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное описание')),
                ('global_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.direction_of_business', verbose_name='Направление бизнеса')),
                ('section', models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.direction', verbose_name='Направление')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.doc_class', verbose_name='Тип документа')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.section', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
