# Generated by Django 5.2.1 on 2025-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_documentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='version_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редакции'),
        ),
    ]
