# Generated by Django 5.2.1 on 2025-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_documentversion_version_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата редакции'),
        ),
    ]
