# Generated by Django 5.2.1 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_document_version_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='word_file',
            field=models.FileField(blank=True, help_text='Необязательное поле. Исходный Word-файл для редактирования.', null=True, upload_to='documents/word/', verbose_name='Исходный Word-файл'),
        ),
    ]
