# Generated by Django 5.0 on 2025-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_presentationslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/versions/word/', verbose_name='Исходный Word-файл'),
        ),
    ]
