# Generated by Django 5.0 on 2025-07-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_documentversion_word_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-version_date', '-uploaded_at']},
        ),
    ]
