# Generated by Django 5.0 on 2025-07-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_documentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_mixed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
