# Generated by Django 5.2.1 on 2025-09-30 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(verbose_name='Дата поступления задачи')),
                ('planned_deadline', models.DateField(verbose_name='Плановый срок завершения')),
                ('actual_deadline', models.DateField(blank=True, null=True, verbose_name='Фактический срок завершения')),
                ('category', models.CharField(choices=[('development', 'Разработка'), ('testing', 'Тестирование'), ('design', 'Дизайн'), ('documentation', 'Документация')], max_length=20, verbose_name='Категория задачи')),
                ('task_type', models.CharField(choices=[('bug', 'Исправление ошибки'), ('feature', 'Новая функция'), ('improvement', 'Улучшение'), ('urgent', 'Срочная задача')], max_length=20, verbose_name='Тип задачи')),
                ('customer', models.CharField(default='Внутренний', max_length=100, verbose_name='Заказчик')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Работник'), ('manager', 'Руководитель'), ('director', 'Директор')], default='employee', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
