# Generated by Django 5.0 on 2025-05-14 09:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('powers', models.CharField(blank=True, choices=[('Опубликован', 'Опубликован'), ('Применяется с', 'Применяется с'), ('Вступает в силу', 'Вступает в силу')], default='Опубликован', max_length=200, null=True, verbose_name='статус')),
                ('power_date', models.DateField(blank=True, null=True, verbose_name='дата статуса')),
                ('current_date', models.DateField(auto_now=True, verbose_name='текущая дата')),
                ('publication_date', models.DateField(default=None, verbose_name='дата публикации в оф. источнике')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.category', verbose_name='категория')),
                ('rubric', models.ManyToManyField(to='reviews.rubric', verbose_name='рубрика')),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
                'ordering': ['-current_date'],
            },
        ),
    ]
